version: 2
defaults: &defaults
  docker:
    - image: 'circleci/node:latest'
jobs:
  lint:
    <<: *defaults  
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}.
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - run:
          name: Run linting
          command: npm run lint
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  publish:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}.
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - checkout
      - run:
          name: Publish package
          command: npm run semantic-release || true

workflows:
  version: 2
  test_and_publish:
    jobs:
      - lint
      - publish:
          requires:
            - lint
          filters:
            branches:
              only: master